DELETE http://localhost:3003/api/blogs/5ea16c97ac416f249ba466ec
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRzYWFyaWthIiwiaWQiOiI1ZWEwMjkxODI0ZjhjMTdjNGUwNmJjMjMiLCJpYXQiOjE1ODc2Mjk0MzF9.jR-RC5syG6wEmwqlNd88-kxdnKo0ZPHuXrAdcGGKcZk